name: API Dev Build and Deploy

#triggers
on:
  push:
  #conditions
    #limit to changes on these branches...
    branches:
      - BackEnd
    #limit to changes in this folder...
    paths:
      - UniversityAPI/**
  pull_request:    
    branches:
      - BackEnd
    paths:
      - UniversityAPI/**
  workflow_dispatch:

#the tasks to complete
jobs:
  #each job will run on a new vm(build agent)
  build:
    #what type of vm will this job be performed on
    runs-on: ubuntu-latest

    steps:
    - name: build-sanity-check
      run: echo "build sanity check"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Checkout The Repo
      uses: actions/checkout@v4

    - name: Dotnet Restore
      run: dotnet restore ./UniversityAPI/

    - name: Dotnet Build
      run: dotnet build --no-restore ./UniversityAPI/
    
    - name: Dotnet Test
      run: dotnet test --no-build --verbosity normal ./UniversityAPI/
    
  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: dockerize-sanity-check
      run: echo "dockerize sanity check"

    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Install Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push to dockerhub
      uses: docker/build-push-action@v5
      with:
        context: ./UniversityAPI/
        push: true
        tags: nedturner613/roe-api-dev:${{ github.sha }} 

  deploy:
    #this job needs to be finished before this one starts
    needs: dockerize
    runs-on: ubuntu-latest

    steps:
    - name: deploy-sanity-check
      run: echo "deploy sanity check"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'roe-api-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.ROE_API_DEV_PUBLISHSETTINGS }}
        images: 'index.docker.io/nedturner613/roe-api-dev:${{ github.sha }}'
