name: UI Build and Deploy

#triggers
on:
  push:
  #conditions
    #limit to changes on these branches...
    branches:
      - devops/deploy
    #limit to changes in this folder...
    paths:
      - Frontend/**
  pull_request:    
    branches:
      - devops/deploy
    paths:
      - Frontend/**
  workflow_dispatch:

#the tasks to complete
jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: dockerize-sanity-check
      run: echo "dockerize sanity check"

    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Install Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push to dockerhub
      uses: docker/build-push-action@v5
      with:
        context: ./Frontend/
        push: true
        tags: nedturner613/roe-test:${{ github.sha }} 

  deploy:
    #this job needs to be finished before this one starts
    needs: dockerize
    runs-on: ubuntu-latest

    steps:
    - name: deploy-sanity-check
      run: echo "deploy sanity check"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'roe-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.ROE_TEST_PUBLISHSETTINGS }}
        images: 'index.docker.io/nedturner613/roe-test:${{ github.sha }}'
