name: dotnet build and test

on:
  push:
    branches: [ "main", "BackEnd", "repository" ]
  pull_request:
    branches: [ "main", "BackEnd", "repository" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies 
      run: dotnet restore University/src
    - name: Build
      run: dotnet build --no-restore University/src
    - name: Test
      run: dotnet test --no-build --verbosity normal University/src